### ISSUE TITLE
The ReSharper plugin deadlock VS when tries to access COM from background thread

### ISSUE THREAD

**Issue by sergeyQx** [stg-tud/kave#27]
Here's the stacktrace when it is called from background thread while ReSharper calculates completion items. 
The UI thread is trying to obtain WriteLock to handle typing at the moment.

```
19c2e484 51393f06 (MethodDesc 51338578 +0xb6 DomainNeutralILStubClass.IL_STUB_CLRtoCOM()), calling clr!StubHelpers::InterfaceMarshaler__ConvertToManaged
19c2e4b0 193d9835 (MethodDesc 1937b258 +0x45 KaVE.VS.FeedbackGenerator.Utils.Names.VsComponentNameFactory.GetWindowName(System.String, System.String)), calling (MethodDesc 1937b094 +0 KaVE.Commons.Model.Names.VisualStudio.WindowName.Get(System.String))
19c2e4e4 189edf35 (MethodDesc 46f9ee88 +0x3d KaVE.VS.FeedbackGenerator.Generators.EventGeneratorBase.get_DTE()), calling 49cf1aa2
19c2e4fc 193d9c1c (MethodDesc 46f9eec0 +0x44 KaVE.VS.FeedbackGenerator.Generators.EventGeneratorBase.get_DTEActiveDocumentName()), calling 49cf1dae
19c2e528 193d9bc0 (MethodDesc 47200fc8 +0x28 KaVE.Commons.Model.Events.IDEEvent.set_ActiveWindow(KaVE.Commons.Model.Names.VisualStudio.WindowName)), calling clr!JIT_WriteBarrierEAX
19c2e538 193d7dc3 (MethodDesc 1937adcc +0xf3 KaVE.VS.FeedbackGenerator.Generators.EventGeneratorBase.Create[[System.__Canon, mscorlib]]()), calling (MethodDesc 46f9eec0 +0 KaVE.VS.FeedbackGenerator.Generators.EventGeneratorBase.get_DTEActiveDocumentName())
19c2e5ac 193d7a03 (MethodDesc 46f9ef88 +0x33 KaVE.VS.FeedbackGenerator.Generators.ReSharper.ActionEventGenerator.FireActionEvent(System.String)), calling (MethodDesc 1937adcc +0 KaVE.VS.FeedbackGenerator.Generators.EventGeneratorBase.Create[[System.__Canon, mscorlib]]())
19c2e5c4 193d77b6 (MethodDesc 46f9ef80 +0x66 KaVE.VS.FeedbackGenerator.Generators.ReSharper.ActionEventGenerator.TrackActivity(System.String, System.String, Int32)), calling (MethodDesc 46f9ef88 +0 KaVE.VS.FeedbackGenerator.Generators.ReSharper.ActionEventGenerator.FireActionEvent(System.String))
19c2e5e0 193d73fc (MethodDesc 37663f58 +0x4c JetBrains.Application.ActivityTrackingNew.UsageStatistics.TrackActivity(System.String, System.String)), calling 49d15b5a
19c2e610 8fd51576 (MethodDesc 46f99b1c +0xfe JetBrains.ReSharper.Feature.Services.CodeCompletion.PostfixTemplates.PostfixTemplatesItemProviderBase`2[[System.__Canon, mscorlib],[System.__Canon, mscorlib]].AddLookupItems(System.__Canon, JetBrains.ReSharper.Feature.Services.CodeCompletion.Infrastructure.LookupItems.GroupedItemsCollector)), calling (MethodDesc 37663f58 +0 JetBrains.Application.ActivityTrackingNew.UsageStatistics.TrackActivity(System.String, System.String))
19c2e638 688fd8ed (MethodDesc 371f5838 +0x55 JetBrains.ReSharper.Feature.Services.CodeCompletion.Infrastructure.ItemsProviderOfSpecificContext`1[[System.__Canon, mscorlib]].JetBrains.ReSharper.Feature.Services.CodeCompletion.Infrastructure.ICodeCompletionItemsProvider.AddLookupItems(JetBrains.ReSharper.Feature.Services.CodeCompletion.Infrastructure.ISpecificCodeCompletionContext, JetBrains.ReSharper.Feature.Services.CodeCompletion.Infrastructure.LookupItems.GroupedItemsCollector, System.Object))
19c2e64c 688fd882 (MethodDesc 6879aadc +0x22 JetBrains.ReSharper.Feature.Services.CodeCompletion.IntellisenseManager+<>c__DisplayClass46.<GetCompletionResult>b__22()), calling 5a20bffa
19c2e664 688fd7c2 (MethodDesc 6879ab60 +0x2a JetBrains.Util.Logging.Logger.CatchIgnoreException[[System.Boolean, mscorlib],[System.__Canon, mscorlib]](System.Func`1<Boolean>))
19c2e694 688fb075 (MethodDesc 37445b64 +0x6f5 JetBrains.ReSharper.Feature.Services.CodeCompletion.IntellisenseManager.GetCompletionResult(JetBrains.ReSharper.Feature.Services.CodeCompletion.CodeCompletionParameters, JetBrains.TextControl.ITextControl, System.Collections.Generic.List`1<JetBrains.ReSharper.Feature.Services.CodeCompletion.Infrastructure.ISpecificCodeCompletionContext>, System.Collections.Generic.List`1<JetBrains.ReSharper.Feature.Services.CodeCompletion.Infrastructure.ISpecificCompletionSorter>)), calling (MethodDesc 6879ab60 +0 JetBrains.Util.Logging.Logger.CatchIgnoreException[[System.Boolean, mscorlib],[System.__Canon, mscorlib]](System.Func`1<Boolean>))
19c2e99c 688f4296 (MethodDesc 37445b58 +0x96 JetBrains.ReSharper.Feature.Services.CodeCompletion.IntellisenseManager.GetCompletionResult(JetBrains.ReSharper.Feature.Services.CodeCompletion.CodeCompletionParameters, JetBrains.TextControl.ITextControl)), calling (MethodDesc 37445b64 +0 JetBrains.ReSharper.Feature.Services.CodeCompletion.IntellisenseManager.GetCompletionResult(JetBrains.ReSharper.Feature.Services.CodeCompletion.CodeCompletionParameters, JetBrains.TextControl.ITextControl, System.Collections.Generic.List`1<JetBrains.ReSharper.Feature.Services.CodeCompletion.Infrastructure.ISpecificCodeCompletionContext>, System.Collections.Generic.List`1<JetBrains.ReSharper.Feature.Services.CodeCompletion.Infrastructure.ISpecificCompletionSorter>))
19c2e9e8 688f41e2 (MethodDesc 66805370 +0x1a JetBrains.ReSharper.Features.Intellisense.CodeCompletion.Sessions.AutomaticCodeCompletionSession+AsyncCompletionExecutor.Work()), calling (MethodDesc 37445b58 +0 JetBrains.ReSharper.Feature.Services.CodeCompletion.IntellisenseManager.GetCompletionResult(JetBrains.ReSharper.Feature.Services.CodeCompletion.CodeCompletionParameters, JetBrains.TextControl.ITextControl))
19c2e9f8 582071ae (MethodDesc 2a72e228 +0x86 JetBrains.Application.InterruptableReadActivity.DoWork())
19c2ea10 3e163180 (MethodDesc 3783545c +0x10 JetBrains.Application.InterruptableActivityCookie..ctor(System.Func`1<Boolean>)), calling clr!JIT_WriteBarrierESI
19c2ea24 58206f5b (MethodDesc 2a72e1f8 +0x5b JetBrains.Application.InterruptableReadActivity.WorkerThreadProc()), calling (MethodDesc 2a72e228 +0 JetBrains.Application.InterruptableReadActivity.DoWork())

```

**Comment by sergeyQx** [comment]
Here's the link to original ReSharper support issue https://jbs.zendesk.com/agent/tickets/703218

**Comment by proksch** [comment]
Hey Sergey, thank you for reporting this issue. We are aware of it, but did not find the time so far to work out the details... :/ You are saying it is a ReSharper issue rather than an incorrect usage of the framework on our side? Unfortunately, I cannot open the support ticket that is linked by you. Did you provide the wrong link or do I lack the permissions to open the ticket?

**Comment by sergeyQx** [comment]
Hey Sebastian, 

The link is not public indeed, I just provided it for future references in case someone needs more details.The problem is inproper use of ReSharper API by KaVE project. The callback to JetBrains.Application.ActivityTrackingNew.UsageStatistics.TrackActivity should return as quick as possible and if called from background should never access Visual Studio COM objects as it will require marshalling to the UI thread and back which might block UI like in the case. 
If you need any assistance feel free to contact me directly.

**Comment by proksch** [comment]
We create our events like this in several other event generators too, I guess the main difference is that these are running in the UI thread when the information is requested.

I'm not quite sure how to decouple the activity tracking from the COM access though. It is crucial for us to get the current window name in which the activity was invoked... one option would be to listen for window changes and to store the current name, but don't think that this is possible. Do you have any idea/suggestion how to guarantee that activity and window name fit together?

> If you need any assistance feel free to contact me directly.

I really appreciate this, but how can I do it? :) It would be awesome, if you could drop me a quick line... you will find my email address on http://www.stg.tu-darmstadt.de/staff/sebastian_proksch/ Thanks!

**Comment by sergeyQx** [comment]
I can see 2 ways:
1. when your code is called enqueue your activity to the UI thread. You may use ReSharper API: JetBrains.Threading.IThreadingEx.ExecuteOrQueue - your code will be code on the UI thread with ReSharper guard making sure there's no other ReSharper activity in callstack.
2. Track changing active windows and when your code is called from ReSharper you'll always have current window at hand.

**Comment by proksch** [comment]
Thanks for the suggestions. Your first suggestion seemed easy to adapt and I quickly implemented it ([see commit](https://github.com/stg-tud/kave/commit/805277e830649019e55920edd7bd314f3ab5aceb)). As a result, the collector still seems to work and it did not hang in the 5min in which I tried it, however, accessing `ReentrencyGuard.Current` (sometimes) results in the following exception: 

```
Cannot create a Dispatcher on thread “JetPool (S) Regular thread #1”:15 because the Dispatcher implements the Single-Threaded Apartment pattern, and this thread is MTA rather than STA.
 
--- EXCEPTION #1/1 [LoggerException]
Message = “Cannot create a Dispatcher on thread “JetPool (S) Regular thread #1”:15 because the Dispatcher implements the Single-Threaded Apartment pattern, and this thread is MTA rather than STA.”
[...]
StackTraceString = “
  at JetBrains.Threading.JetDispatcher..ctor()
     at JetBrains.Util.Concurrency.WinJetDispatcher..ctor()
     at JetBrains.Util.Concurrency.WinJetDispatcher.WinJetDispatcherStaticMethods.JetBrains.Util.Concurrency.IJetDispatcherStaticMethods.CreatePerThreadInstance()
     at JetBrains.Threading.JetDispatcher.get_CurrentDispatcher()
     at JetBrains.Threading.ReentrancyGuard..ctor()
     at JetBrains.Threading.ReentrancyGuard.get_Current()
     at KaVE.VS.FeedbackGenerator.Generators.ReSharper.ActionEventGenerator.FireActionEvent(String actionId)
     at ...
```
(see [full stack trace](http://pastebin.com/dPbn92dZ))

Is there a recommended way of how to get access to the `IThreading` object?

**Comment by sergeyQx** [comment]
True way of obtaining ReSharper components is creating your own component and injecting it as constructor parameter. If you have ISolution you may call solution.GetComponent<IThreading>(), but it is not recommended

**Comment by proksch** [comment]
All our generators are marked as `[ShellComponent]` and are initialized by ReSharper, so I can define the dependency for injection in the constructor as suggested. Does the [updated generator implementation](https://github.com/stg-tud/kave/blob/fix-COM-deadlock/feedback-generator/KaVE.VS.FeedbackGenerator/Generators/ReSharper/ActionEventGenerator.cs#l53) meet your expectation?

**Comment by sergeyQx** [comment]
Yes, looks good.

**Comment by proksch** [comment]
Awesome. Thanks for your help!

**Comment by proksch** [comment]
Fixed in master.

The same problem may occur in several other event generators too, I created a task in our internal issue tracker to provide a general fix in the next release.
